name: tensorflow101
dependencies:
  - python=3.6
  - tensorflow=1.10.0
  - keras
  - matplotlib
  - notebook
  - requests
  - pandas
  - pip:
    - azure-cli
    - azureml-sdk[automl,contrib,notebooks]=0.1.80
    - tensorflow-serving-api
